### ISSUE TITLE
webvisor

### ISSUE THREAD

**Issue by i4got10** [narkq/react-yandex-metrika#11]
Привет!

Есть ли возможность использовать вебвизор только для определенных страниц?
В контексте SPA метрика инициализируется только один раз при старте приложения

**Comment by narkq** [comment]
Вроде бы это можно указать в настройках вебвизора; впрочем, я не в курсе, правильно ли это работает на SPA-сайтах.

**Comment by narkq** [comment]
Если вариант с настройкой вебвизора не устраивает, то боюсь это вопрос скорее к товарищам из яндекс метрики. По крайней мере, в документации метода включения/отключения вебвизора я не нашел.
