### ISSUE TITLE
Сбои подсчета отказов и глубины показа

### ISSUE THREAD

**Issue by Dictory** [narkq/react-yandex-metrika#13]
При переходе с версии 1.x на 2.3 отказы стали равны 99-100%, глубина просмотров 1.
Использую `ym('hit', this.props.location.pathname);` в `componentDidUpdate`;

**Comment by Dictory** [comment]
@narkq @urakozz @priezz can someone help me?

**Comment by urakozz** [comment]
Пфф, поди знай, тут кода то почти нет, ломаться нечему. И у меня всякие отказы сами работают без доп магии, там есть настройка типа «отслеживать изменение хэша в адресной строке»

**Comment by urakozz** [comment]
@Dictory here is my config, FYI
```
trackLinks: true,
trackHash: true,
accurateTrackBounce: true,
```

**Comment by Dictory** [comment]
@urakozz Да вот и странно, в 1.x метод `hit` работал, а теперь нет =)
Спасибо, попробую с конфигом.

**Comment by narkq** [comment]
@Dictory Насколько мне известно, такое бывает, когда в методе hit передается неверный реферер (т. е. например пустой вместо предыдущей страницы - в этом случае внутренние переходы будут засчитываться как прямые, а просмотры предыдущих страниц будут засчитываться как отказы).

**Comment by Dictory** [comment]
@narkq Спасибо за ответ. Но в hit передается все правильно, к тому же, в версии 1.x все работало верно.

**Comment by Dictory** [comment]
@urakozz не помогает мне такой способ

**Comment by narkq** [comment]
@Dictory я бы все-таки проверил, действительно ли передается все правильно. И вообще, отправляются ли хиты.
Самый простой способ сделать это - включить логирование отправки событий в Метрику.
Для этого можно:

- либо поставить cookie `debug=1`;
- либо добавить на страницу инлайн-скрипт `window._ym_debug=1`;
- либо добавить к URL страницы query-параметр `_ym_debug=1`.

Тогда библиотека Метрики начнет записывать в консоль что-то типа такого
![react-yandex-metrika-issue-13](https://user-images.githubusercontent.com/705650/36969975-05652796-2078-11e8-9fbc-24709bcfef85.png)
