### ISSUE TITLE
TypeError: window[_constants.accountListName] is undefined

### ISSUE THREAD

**Issue by romanown** [narkq/react-yandex-metrika#18]
if (typeof window !== 'undefined') {
 is not helped
is error bellow

ymAsyncProxy
/node_modules/react-yandex-metrika/lib/index.js:41

  38 |     args[_key2] = arguments[_key2];
  39 | }
  40 | 
> 41 | window[_constants.accountListName].forEach(function (id) {
  42 |     var trackerVersion = window[(0, _constants.trackerVersionName)(id)];
  43 |     var callbackQueue = window[(0, _constants.callbackQueueName)(trackerVersion)];
  44 |     if (callbackQueue) {

ym
/node_modules/react-yandex-metrika/lib/index.js:56

  53 | 
  54 | function ym() {
  55 |     if (isBrowser) {
> 56 |         ymAsyncProxy.apply(undefined, arguments);
  57 |     }
  58 | }
  59 | 

./src/RoutesContainer.js/__webpack_exports__.a<
/src/RoutesContainer.js:67

  64 | export default withRouter(props => {
  65 |   const isMain = props.location.pathname === '/'
  66 |   if (typeof window !== 'undefined') {
> 67 |   ym('hit', props.location.pathname);
  68 | }
  69 |   
  70 |   return (

**Comment by romanown** [comment]
в момент компиляции такое. TypeError: window[_constants.accountListName] is undefined

**Comment by romanown** [comment]
`TypeError: window[_constants.accountListName] is undefined
ymAsyncProxy
/node_modules/react-yandex-metrika/lib/index.js:41

    args[_key2] = arguments[_key2];
 }
 
window[_constants.accountListName].forEach(function (id) {
     var trackerVersion = window[(0, _constants.trackerVersionName)(id)];
     var callbackQueue = window[(0, _constants.callbackQueueName)(trackerVersion)];
   if (callbackQueue) {

ym
/node_modules/react-yandex-metrika/lib/index.js:56

 function ym() {
  if (isBrowser) {
       ymAsyncProxy.apply(undefined, arguments);
     }
 }
 
./src/RoutesContainer.js/__webpack_exports__.a<
D:/npm/dress/dress/src/RoutesContainer.js:70

<div style={{height: isMain ? '100%' : 'auto'}}>
<YMInitializer accounts={[49433788]} />
if (typeof window !== 'undefined') {
ym('hit', props.location.pathname)	
 }
  <Switch>`

**Comment by romanown** [comment]
но при переносе кода в другие места эта же ошибка выходила при попытке перехода между страницами сайта. используется серверный рендеринг.

**Comment by romanown** [comment]
скрин
![default](https://user-images.githubusercontent.com/7169357/42218472-5ccf7b0a-7ed1-11e8-86a8-9da62a65575f.png)

**Comment by narkq** [comment]
Я правильно понимаю, что `RoutesContainer.js` - это компонент роутера?
Не совсем ясно, что там за if-statement в перемешку с JSX?

Вам нужно по сути написать код, который сможет реагировать на изменения роута и посылать соответствующие события. Это ни в коем случае нельзя делать в методе `render`. Как правило, это делают в методе `componentWillReceiveProps` (вот как например в библиотеке, ссылку на которую Вы давали https://github.com/sonaye/react-with-analytics/blob/master/src/withAnalytics.js#L23 ). Впрочем, `componentWillReceiveProps` вроде как [deprecated](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), так что может быть можно просто подписаться на события навигации через https://github.com/ReactTraining/history например.

**Comment by romanown** [comment]
наверное надо было полностью привести код как оно сейчас.
`const HistoryListener = withRouter(class extends React.Component {
  componentDidMount() {
    this.props.history.listen((props) => {
	  ym('hit', this.props.location.pathname);	
      window.scrollTo(0, 0)
    })
  }
  render() {
    return null
  }
})
export default withRouter(props => {
  return (
    <div style={{height: isMain ? '100%' : 'auto'}}>
	<YMInitializer accounts={[49433788]} />
      <HistoryListener />
      <Switch>
		<Route exact path="/" component={Home} />`

**Comment by romanown** [comment]
а если сделать
`componentWillReceiveProps() {
		  ym('hit', this.props.location.pathname);	  
  }`
вообще никакая статистика не отсылается

**Comment by narkq** [comment]
Так все-таки в состоянии "как оно сейчас" работает? Или такая же ошибка?

Если такая же ошибка, то скорее всего это связано с тем, что к тому времени, как срабатывает `HistoryListener.componentDidMount`, не успевает отработать `YMInitializer.componentDidMount` (который, собственно, и создает глобальные объекты типа `window[_constants.accountListName]`).

Чтобы такого не происходило, можно поместить `YMInitializer` внутрь `HistoryListener`-а (т.к. метод `componentDidMount` вызывается в порядке, обратном иерархии компонентов). Например, так:
```
const HistoryListener = withRouter(
  class extends React.Component {
    historyUnlisten = null

    componentDidMount() {
      this.historyUnlisten = this.props.history.listen((location, action) => {
        ym('hit', `${location.pathname}${location.search}${location.hash}`)
      })
    }

    componentWillUnmount() {
      this.historyUnlisten()
    }

    render() {
      return <YMInitializer accounts={[49433788]} />
    }
  }
)

export default withRouter(
  props => {
    return (
      <div>
        <HistoryListener />
        <Switch>
          <Route exact path="/" component={Home} />
          ...
        </Switch>
        ...
      </div>
    )
  }
)
```

**Comment by romanown** [comment]
как сейчас срабатывает не всегда. то есть не все переходы показываются.

**Comment by romanown** [comment]
ибо дидмоунт вызывается не при всех переходах. сделал как Вы написали, но так вообще перестали считаться переходы.

**Comment by narkq** [comment]
> ибо дидмоунт вызывается не при всех переходах

Ох. Он и не должен. Нужно сделать так, чтобы `componentDidMount` для компонентов `HistoryListener` и `YMInitializer` вызывался (желательно) ровно один раз на перезагрузку страницы. После этого при навигации через роутер должен вызываться только обработчик, переданный в `history.listen`.

**Comment by narkq** [comment]
Какая версия react-yandex-metrika подключена?
Возможно, я кое-что сломал в 2.4.0 (или оно вообще не работало для случая, когда серверный код собирается webpack-ом).

**Comment by romanown** [comment]
неделю назад установлена. там ошибка не только при компиляции. а если и проходит, то при посещении страницы. в зависимости от того в какое место я ставлю вызов ym.

**Comment by romanown** [comment]
у меня стоит реакт-креате-апп.

**Comment by romanown** [comment]
"version": "2.3.0"

**Comment by romanown** [comment]
судя по реакции немаловажно куда ставить и первый элемент и отправитель хита.

**Comment by romanown** [comment]
после обновления все работает. спасибо. это единственный на данный момент найденный мною компонент модуль для react reactjs для отправки сообщения в яндекс метрику о совершенном переходе ya.metrika hit для SPA сайта. написал так чтобы другие нашли эту страницу.
