### ISSUE TITLE
В версии v2.4.0 ломается минификацию проекта

### ISSUE THREAD

**Issue by vrozaev** [narkq/react-yandex-metrika#19]
@narkq

Проект падает с такой ошибкой:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/react-yandex-metrika/src/constants.js:3 

Read more here: http://bit.ly/2tRViJ9

```

Кажется проблема в коммите https://github.com/narkq/react-yandex-metrika/commit/e3adf87bc2cac62b047a159ed445fb2350a80d39

**Comment by vrozaev** [comment]
Отбой, не так импортировали.

**Comment by vrozaev** [comment]
@narkq вот репозиторий с воспроизведением:

https://github.com/vrozaev/https-github.com-narkq-react-yandex-metrika-issues-19

**Comment by narkq** [comment]
Опубликовал 2.4.1
Посмотрите, все ли хорошо, пожалуйста.

**Comment by vrozaev** [comment]
@narkq в 2.4.1 все исправилось.
