### ISSUE TITLE
how to access ecommerce.dataLayer ?

### ISSUE THREAD

**Issue by Zummer** [narkq/react-yandex-metrika#3]
```
if (inBrowser() && window.ym && client.YandexMetrikaID) {
      window.ym.init([client.YandexMetrikaID], {
        clickmap: true,
        trackLinks: true,
        accurateTrackBounce: true,
        webvisor: true,
        ecommerce: "dataLayer"
      });
    }
```

**Comment by narkq** [comment]
You should put this snippet
```
window.dataLayer = window.dataLayer || [];
```
right before `ym.init`.

Or I could probably put it inside of `ym.init`? Which one do you prefer?

**Comment by narkq** [comment]
Also, maybe I got you wrong.
What exactly do you mean by "access"?

**Comment by Zummer** [comment]
Я новичок и только разбираюсь, обратившись к dataLayer получил undefined. Да, спасибо, разобрался уже. 
I am a newbie and just beginning to understand, for the first time referring to dataLayer was undefined. Yes, thanks, I already understood.
